apiVersion: v1
kind: Secret
metadata:
  name: ai-service-secret
data:
  # These are encoded base64 using command "echo -n '<api_key>' | base64" and "echo -n '<org_id>' | base64"
  OPENAI_API_KEY: ""
  OPENAI_ORG_ID: "" 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
      # annotations: 
      #   consul.hashicorp.com/connect-inject: "true"
    spec:
      # serviceAccountName: ai-service
      containers:
      - name: ai-service-container
        image: vishallokam/ecommerce-ai-service:3.0
        ports:
        - containerPort: 5000
        env:
        - name: OPENAI_API_KEY 
          valueFrom: 
            secretKeyRef:
              name: ai-service-secret
              key: OPENAI_API_KEY
        - name: OPENAI_ORG_ID 
          valueFrom: 
            secretKeyRef:
              name: ai-service-secret
              key: OPENAI_ORG_ID
        resources:
          requests:
            cpu: 20m
            memory: 46Mi
          limits:
            cpu: 30m
            memory: 65Mi

---

apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: default
  labels:
    app: ai-service
spec:
  type: ClusterIP
  selector:
    app: ai-service
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000

# ---

# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: ai-service
#   namespace: default
# automountServiceAccountToken: true
# ---

# apiVersion: consul.hashicorp.com/v1alpha1
# kind: ServiceDefaults
# metadata:
#   name: ai-service
#   namespace: default
# spec:
#   protocol: "http"

---

apiVersion: v1
kind: Service
metadata:
  name: ai-service-externalname
  namespace: default
spec:
  type: ExternalName
  externalName: api.openai.com
