apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
data:
  # This encoded base64 <Mongodb connection string> || "echo -n '<mongo_conn_string>' | base64"
  CONNECTION_STRING: ""
   
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      # annotations: 
      #   consul.hashicorp.com/connect-inject: "true"
    spec:
      # serviceAccountName: auth-service
      containers:
      - name: auth-service-container
        image: vishallokam/ecommerce-auth-service:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7070
        env:
        - name: CONNECTION_STRING 
          valueFrom: 
            secretKeyRef:
              name: auth-service-secret
              key: CONNECTION_STRING
        resources:
          requests:
            cpu: 20m
            memory: 46Mi
          limits:
            cpu: 30m
            memory: 65Mi

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
  - name: http
    protocol: TCP
    port: 7070
    targetPort: 7070

# ---

# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: auth-service
#   namespace: default
# automountServiceAccountToken: true

# ---

# apiVersion: consul.hashicorp.com/v1alpha1
# kind: ServiceDefaults
# metadata:
#   name: auth-service
#   namespace: default
# spec:
#   protocol: "http"
